### ISSUE TITLE
B route waypoints do not work properly in EA

### ISSUE THREAD

**Issue by KazakstanSaatana** [aronCiucu/DCSTheWay#103]
Hello, currently TheWay sets coordinates for the F-15E in the B route, which is currently not enabled yet in this version of the Strike Eagle
![Screenshot_2023-06-30-04-07-21-59_f541918c7893c52dbd1ee5d319333948](https://github.com/aronCiucu/DCSTheWay/assets/138176617/c97de09e-2a0a-4aef-bb3e-0778d82ebf37)

Waypoints in the B route are not displayed on the radar pages and can't be cycled through, making it impossible designate for example a radar map or slew the TPOD with B route waypoints.

I ask to change the waypoint input to A route, which works, rather than B route.

Thanks a lot!

**Comment by blueberrypi-studio** [comment]
Hey man, there's no official release yet, my version has the f15E. this is a bug in the f15e. It will be fixed in two weeks (tm)

**Comment by aronCiucu** [comment]
In the next release, you can choose between route A and B
