### ISSUE TITLE
New version 210 no longer works with A-10C II

### ISSUE THREAD

**Issue by Quozl1** [aronCiucu/DCSTheWay#105]
Any entry using version 210 returns CDU input error for the A-10C II where as version 200 works perfectly.

**Comment by blueberrypi-studio** [comment]
Error likely here https://github.com/aronCiucu/DCSTheWay/commit/ba6b4a48b8927df27385d5fe76b637a50a26eb23

**Comment by aronCiucu** [comment]
Fixed with 2.1.1
