### ISSUE TITLE
JavaScript Error

### ISSUE THREAD

**Issue by ocgadmin** [aronCiucu/DCSTheWay#106]
Just upgraded to 2.1.2 and I get this error

![Screenshot 2023-07-22 224144](https://github.com/aronCiucu/DCSTheWay/assets/49978449/02e6d35e-0d50-4030-9797-39dec089d3d5)

**Comment by aronCiucu** [comment]
Hi, can you show me the contents of the Scripts folder in Saved Games?

**Comment by blueberrypi-studio** [comment]
Yea this is the same thing I get, it still kinda works if you spam the transfer button for some reason, my scripts folder is the same as what it was using previous versions

**Comment by aronCiucu** [comment]
If you can send me instructions on how to trigger the error it would be appreciated, this way i can find the cause

**Comment by ocgadmin** [comment]
[Scripts.zip](https://github.com/aronCiucu/DCSTheWay/files/12137272/Scripts.zip)

**Comment by ocgadmin** [comment]
Think I found a fix, installed updated Node.js now working
https://nodejs.org/en

**Comment by blueberrypi-studio** [comment]
I am testing this now, but surely this should work independently of the user's system, a good majority of users will not have node.js installed at all.

**Comment by ocgadmin** [comment]
Sorry my programming skills are nil. Just did a search on the problem and all I found was a problem between node.js 16 and 17.
So ran it and problem seems to be gone. Sorry I cannot be more help

**Comment by blueberrypi-studio** [comment]
@aronCiucu I have updated, still cannot get it to work, to reproduce all I do is hit transfer. Any relevant info you need regarding versions you need from me let me know. Definitely is a result of your last patch (maybe your fix has to do with opening 2 instances?). 
![image](https://github.com/aronCiucu/DCSTheWay/assets/75970722/1a81af56-529d-4dfa-8968-0c0f030bf9cb)

**Comment by aronCiucu** [comment]
How did you install the new version of TheWay? Did you run the newer installer? It might have something to do with the update process because the transfer is working fine for me and some other people who have installed it for the first time

**Comment by blueberrypi-studio** [comment]
Yea the new installer, I can test a fresh install now standby

**Comment by ocgadmin** [comment]
ok

**Comment by blueberrypi-studio** [comment]
fresh install didn't work, but I didn't change theway.lua or the line of code in export.lua, have those changed recently

**Comment by ocgadmin** [comment]
not that I'm aware

**Comment by ocgadmin** [comment]
OK 
new install tested on a mission non VR and all ok
Tested on mission in VR and ok
Just wish I didn't have to Alt Tab to name the waypoints before loading

**Comment by blueberrypi-studio** [comment]
@aronCiucu version 2.1.3 works good. I deleted the install folder in roaming first before install and it works like a charm

**Comment by aronCiucu** [comment]
Interesting, then i might be a problem with how the updating process works

**Comment by aronCiucu** [comment]
Please reopen the issue if you still whitness it on the latest release
