### ISSUE TITLE
Interface Blanks out if more than 5 WPTs

### ISSUE THREAD

**Issue by Hbomb101** [aronCiucu/DCSTheWay#109]
So the issue i always have is that if i have more than 5 wpts on the App screen. 
I can only use those points once, as it Blanks out/crashes the Way. 
I then have to restart the App...
Previous builds could handle useage all day, and i could Alt-Tab and reuse it.

**Comment by Rezzemy** [comment]
The current build has an issue with CPU usage whilst traveling at the moment, i recommend doing way points whilst still on the runway or starting the transfer sequence while in f10.

I have a pull request with a fix for this but that will take some time to get into a release.

**Comment by Hbomb101** [comment]
I have always done waypoints while stationary/ starting up.  
This issue is that the APP crashes/ Blanks out after use (Alt-Tab Back from Minimized) with more than 5 waypoints on the little screen (more than 5 Scrolls down). 
There is no Issue with re-using the Waypoints again with 5 or less. 
So it must be an issue with the App scrolling or Minimizing (Alt-Tab) maybe... something like that?

**Comment by blueberrypi-studio** [comment]
@Hbomb101 and @Rezzemy are you both using the latest version? The Hotfix patch from a few weeks ago (that's not the issue, just want to figure out what version you are on) so I can test/replicate/fix the issue (I have my own problems with the latest release which do not seem universal

**Comment by Rezzemy** [comment]
> @Hbomb101 and @Rezzemy are you both using the latest version? The Hotfix patch from a few weeks ago (that's not the issue, just want to figure out what version you are on) so I can test/replicate/fix the issue (I have my own problems with the latest release which do not seem universal

I’ve tested tested both latest source and latest release (assuming there’s a difference) as well as my current build, before and after throttling the ‘datareceived’ ipclistener. I’ve experienced the same issue on the latter 3 versions in the following conditions

- the jet is flying in the air <100 kts 
- the more waypoints you add the worst it gets. not exponentially but the load seems to pile on for some odd reason.
- Current view is F1 view

I’m hoping this is reproducible in your findings and that your results support my findings.

**Comment by Rezzemy** [comment]
> I have always done waypoints while stationary/ starting up. This issue is that the APP crashes/ Blanks out after use (Alt-Tab Back from Minimized) with more than 5 waypoints on the little screen (more than 5 Scrolls down). There is no Issue with re-using the Waypoints again with 5 or less. So it must be an issue with the App scrolling or Minimizing (Alt-Tab) maybe... something like that?

Might be a state handling issue from what he's saying, but this does seem non universal, i cant seem to replicate it. 5 waypoints and minimizing + alt tab backing to it doesnt seem to do very much, and the performance profiler isn't really showing anything either.

as a sort of interim "what-to-do", could you try deleting everything in "%appdata%\Roaming\theway" and then try again Hbomb?

**Comment by Hbomb101** [comment]
Latest version. cleaned out the roaming folder. Still when I do **_More than 5_** Waypoints and fill the App screen is will Blank out or Crash after use - Minimized - Alt-Tab....

**Comment by aronCiucu** [comment]
Hi, try version 2.1.3 and maybe record a video of the behavior

**Comment by Hbomb101** [comment]
Seems to work fine now, have Minimized and even shut down DCS and come back to and it Doesn't  Blank out or crash. Good job.
