### ISSUE TITLE
save/load waypoint lists

### ISSUE THREAD

**Issue by FalcoGer** [aronCiucu/DCSTheWay#11]
Add an option to save the waypoints to a text file or load them from such a file.

**Comment by momcilo78** [comment]
+

**Comment by BlueFinBima** [comment]
@FalcoGer / @l33n0x There is code [here](https://github.com/BlueFinBima/DCS-The-Way/releases/latest) which is pre-release.  The code in the fork should give some ability to achieve what you're seeking. See the notes at the end of the release notes.

**Comment by aronCiucu** [comment]
This was added officially in the latest release
