### ISSUE TITLE
VR Usage: Still asks for seat

### ISSUE THREAD

**Issue by PatZab** [aronCiucu/DCSTheWay#110]
Unfortunately it asks everytime I am going to transfer the waypoints, in which seat I am. Althoug I set the check for "Assume the pilot seat from now"

Furthermore there is no crosshair for aiming on the map. I have to use the scratchpad overlay to do so.

**Comment by korruptcow** [comment]
I find i have to assume pilot seat a few times before it sticks.

**Comment by aronCiucu** [comment]
Hi, check the path `C:\Users\USER\AppData\Roaming\theway` and see if you have a `config.json` file in there

**Comment by PatZab** [comment]
The config.json file is there with this entry:

```
{
	"hideDialogs": true
}
```

**Comment by aronCiucu** [comment]
And what module are you having issues with?

**Comment by PatZab** [comment]
I am using it with the AH-64D Apache Module. I have not tested it with other modules yet.

**Comment by PatZab** [comment]
I will try with 2.1.3. I had 2.1.2 installed since the latest version was not released back then.

**Comment by PatZab** [comment]
> I will try with 2.1.3. I had 2.1.2 installed since the latest version was not released back then.

I tried it in non-VR and it seems to work. I will try in VR later and let you know.

**Comment by PatZab** [comment]
> Very weird... I am not able to reproduce the issue, but are you sure you have the latest version 2.1.3 installed? I remember there were some issues in the past but they were resolved in later releases

So everything works fine when you use the "Transfer to DCS" button. But if you use the short cut for transferring it asks everytime. It does not matte if in VR or not.

**Comment by aronCiucu** [comment]
Hello all, I finally got to the bottom of this issue and fixed it for the next release
