### ISSUE TITLE
Black Box in F10 map hiding central dot

### ISSUE THREAD

**Issue by Kiwi0ne** [aronCiucu/DCSTheWay#111]
Since last release I know have a black box which hides the dot in the center of the screen. This issue has been reported by a few users in DCS forums.

**Comment by aronCiucu** [comment]
Hi, please check if the latest version 2.1.3 does the same things, I for one cannot reproduce it but I have changed a few things to see if it has any effect.

**Comment by aronCiucu** [comment]
@Kiwi0ne can you confirm if this is also the case with the latest 2.3.0 version?
