### ISSUE TITLE
[AH64] Waypoints get input multiple times

### ISSUE THREAD

**Issue by FalcoGer** [aronCiucu/DCSTheWay#112]
When marking way points and deleting them in TheWay, then they will still be transfered, even though they have been deleted.
Moreover when marking waypoints and transferring them, then get in a new aircraft and transferring again, it transfers the sequence of points twice. When then getting into a new aircraft, it transfers each point three times and so on.

Only tested with AH64.

**Comment by FalcoGer** [comment]
Seems to have been fixed in 0352ab078dfc859fb923dd6b6ffd56c4941ae17a, but no hotfix is available in releases.

**Comment by korruptcow** [comment]
Also the same with f-18 even after deleting the previous points. I think it has something to do with the ability not having to confirm anymore.

**Comment by aronCiucu** [comment]
Fixed in the latest release
