### ISSUE TITLE
AH-64 multiplayer - reslotting causes multiple waypoints

### ISSUE THREAD

**Issue by toadmcfrog** [aronCiucu/DCSTheWay#116]
In AH-64 multiplayer, it seems that each new Apache you slot into creates an additional set of waypoints on top of the set in the initial aircraft.  So, for instance: 

- Slot into your first aircraft, add 4 waypoints
- Reslot for any reason in a new aircraft
- In the new aircraft, the waypoints you previously selected will be added twice - in addition to waypoints 1-4, you will now have 5-8 in the exact same spots 
- Reslot for any reason in a new aircraft
- In the 3rd aircraft, the previously selected waypoints will be added three times - 1-4, 5-8, and 9-12.  
- Continue add naseum. 

This has only been tested in multi-crew on multiplayer servers, so it might not happen with a single crewman and George.

**Comment by aronCiucu** [comment]
Hello, are you using VR or 2D? Are you also using the keybinds to transfer?

**Comment by toadmcfrog** [comment]
I'm in VR and have used the keybinds to add waypoints, but I'm using the UI to transfer them to the aircraft.

**Comment by aronCiucu** [comment]
Please try the latest version and see if this behavior is still present

**Comment by blueberrypi-studio** [comment]
@aronCiucu I had this issue when I added the eagle, it was something to do with the seat selection window not having an elseif or something like that, even though I'd added the eagle my poor coding made the hornet double waypoints. It's in my discord DM history with you I think, I'll check

I can't confirm this bug though, I'm unable to test for a week or so

**Comment by aronCiucu** [comment]
I see. I have done some changes to the seat selection logic, it should be more reliable now. Although it would be good to confirm if this is actually the case and the issue is solved

**Comment by aronCiucu** [comment]
Please reopen if issue still exists
