### ISSUE TITLE
M-2000C : Altitude problem on waypoints

### ISSUE THREAD

**Issue by yakisyst3m** [aronCiucu/DCSTheWay#117]
Hello, thanks for the latest patch, it solves some problems. However on the M-2000C, it does not add waypoint elevations.
I see in real time that the app turns the knob to change the coordinates then turns to "D/RLT" instead of "ALT" to change the altitude.

**Comment by blueberrypi-studio** [comment]
I believe it's been patched, not implemented yet https://github.com/aronCiucu/DCSTheWay/pull/115
