### ISSUE TITLE
Allow users to specify at which point new waypoints are entered

### ISSUE THREAD

**Issue by FalcoGer** [aronCiucu/DCSTheWay#12]
Sometimes people want their waypoints appended to the end of a flight plan, for example if the mission has already waypoints on specific points, such as air fields or bullseye and you don't want to overwrite them. It would be nice if you could start the input process from any point in the existing list.

**Comment by jonsky7** [comment]
For most Jets "The Way" starts inputting the selected waypoints in the one after the one is currently selected.
ie, you have waypoint 4 selected, TheWay starts inputting at waypoint 5.

Only the Ka-50 doesn't do this as it only has 6 saveable waypoints.
