### ISSUE TITLE
F16C waypoints bug

### ISSUE THREAD

**Issue by Backspacegun** [aronCiucu/DCSTheWay#120]
It seems that in the F16C setting waypoint 1-25 seems to work, but switching to 26 and up makes it skip LAT and starts inputting all the numbers into LANG meaning it fails to input all the waypoints.

It does still skip through the steerpoints but still only inputs into LANG.

Same waypoints work on steerpoint 1-5 (i've only tested those).

Really annoying since in the f16, waypoint 26 and up is used for slewing the Targeting pod when ground pounding.

**Comment by blueberrypi-studio** [comment]
Waypoints 26-30 are reserved for markpoints and are made differently

That's not an issue with the way :-)

Out of curiosity why do you have so many waypoints

**Comment by Backspacegun** [comment]
Aah, thats slightly annoying, i'll have to keep filling those out manually then, my friends in the F18 use this program for their markpoints on enemies, so i had hoped it would work in the F16 too.

I use this many steerpoints because i'm blind as a bat when it comes to spotting airfields (don't ask me why), so i have 6 steerpoints set on the beginning of the most used runways in my current mission/server.
But when i'm ground pounding i set a (as you've called it) Markpoint on my target to slew my TGP pod to that target, saves some time searching for SA18 launcher or other stuff that is hard to spot. Hence why i was confused/annoyed when the program didn't work for that.

**Comment by blueberrypi-studio** [comment]
You can drop JDAMs on regular waypoints (or CBU 103/5s or JSOWs)
