### ISSUE TITLE
Right clicking top of window makes it freeze up.

### ISSUE THREAD

**Issue by Backspacegun** [aronCiucu/DCSTheWay#122]
Right clicking the top of the window open the menu to resize, move & exit, but the window doesn't close, the buttons don't do anything and i lose the ability to click on the main window so i have to restart the program.

**Comment by 2568XingTong** [comment]
me either do u know how to deal with it now？

**Comment by Backspacegun** [comment]
> me either do u know how to deal with it now？

Nope, i just stopped right clicking the window, and when i do i have to restart it.

**Comment by blueberrypi-studio** [comment]
It doesn't need to be resized (I'm pretty sure you can't.) And it has the close button with a left click which works fine. So just don't right click it and it'll be fine 😂

**Comment by Backspacegun** [comment]
> It doesn't need to be resized

I didn't wanna resize it, i can force that if i want, i wanted to remove it from always on top, since my right screen is already full of things i have to have open for dcs, TheWay is the only one that is forced ontop of everything else, so if i wanna google something, the window just blocks part of my screen, only way around that is minimizing it. 



> So just don't right click it and it'll be fine

Like i said in my reply to the other person, i stopped right clicking yes, but it being a bug or whatever, that you need to restart the program if you do is annoying and should honestly be looked at, hence why i made this issue.
(Disclaimer: I know this is a mod and i don't pay for it, so i shouldn't expect anything, but from my POV, if i make something, i want it to be perfect.)

**Comment by aronCiucu** [comment]
Hello, good find @Backspacegun , this has been fixed and will be included in the next release
