### ISSUE TITLE
[Question] How to determine device number and keycode?

### ISSUE THREAD

**Issue by FalcoGer** [aronCiucu/DCSTheWay#124]
Hi, I'm currently working on a C# project that makes use of the DCS TheWay tcp listener. Using the keycodes and device numbers I found in your project, I was able to input coordinates of my own.
I was able to guess a few keycodes, for example to input the point type for the AH64, but I lack an understanding of what exactly it means.

How do you find out the `device` numbers and `code` to be sent? What do the other fields in the command structure mean? What is `delay`? Is it the time between key press and release, or the time between release and the next press? What is `activate`?

Thanks.

If you're interested, you can find the project [here](https://github.com/FalcoGer/CoordinateConverter).

**Comment by blueberrypi-studio** [comment]
![image](https://github.com/aronCiucu/DCSTheWay/assets/75970722/fbb1e87d-4b0a-407d-b681-8061282582a0)

the right hand column, won't take much for you to figure out what code, device and activate are (activate is the 1 or -1)

can be found by going into controls and hitting "make HTML" button on the bottom

**Comment by FalcoGer** [comment]
Thank you.

**Comment by FalcoGer** [comment]
@blueberrypi-studio 

I'm not quite sure how to interpret that data.

For example the A10-II has in src/moduleCommands/a10.js the keycodes.
I exported the HTML file from DCS. When I search the file for say the keycode for "r", which is 3044, then only these show up

Combos | Command | Category | Hash
-- | -- | -- | --
  | VHF AM Secondary Knob: 121.5 Guard Frequency Mode | VHF AM Radio (ARC-210) Control Panel | d3044pnilunilcd55vd0.6vpnilvunil
  | VHF AM Secondary Knob: 243 Guard Frequency Mode | VHF AM Radio (ARC-210) Control Panel | d3044pnilunilcd55vd0.5vpnilvunil
  | VHF AM Secondary Knob: MAN Mode | VHF AM Radio (ARC-210) Control Panel | d3044pnilunilcd55vd0.3vpnilvunil
  | VHF AM Secondary Knob: PRST Mode | VHF AM Radio (ARC-210) Control Panel | d3044pnilunilcd55vd0.2vpnilvunil

However the actual "r" key on the CDU has this code

Combos | Command | Category | Hash
-- | -- | -- | --
LCtrl - LWin - R; LCtrl - LShift - R | CDU R Key | CDU panel | d1271pnilu1271cdnilvdnilvpnilvunil

How am I supposed to figure out the device (9) and key code (3044) from this line?

If this is now how you do it, then how do you do it?

**Comment by FalcoGer** [comment]
I figured it out. It's in `Eagle Dynamics\DCS World OpenBeta\Mods\aircraft\<type>\Cockpit\Scripts\clickabledata.lua` and `Eagle Dynamics\DCS World OpenBeta\Mods\aircraft\<type>\Cockpit\Scripts\devices.lua`
