### ISSUE TITLE
Show version somewhere

### ISSUE THREAD

**Issue by GoldenGnu** [aronCiucu/DCSTheWay#125]
Figuring out what version you have of TheWay is really hard, making it very hard to know if you need to update or not.
So either showing the version number somewhere or some kind of automatic check for new versions would be great.

Thank you very much for making TheWay, it really makes DCS so much more enjoyable.

**Comment by aronCiucu** [comment]
Hello @GoldenGnu , the version number will be shown in the title bar starting with the next release
