### ISSUE TITLE
lost the way in the game

### ISSUE THREAD

**Issue by 2568XingTong** [aronCiucu/DCSTheWay#126]
never had been this situation,when i in the dcs,the way is closed itself,and it cant be found anywhere on the desktop,and there is no way to reopen it,but it shows that it it still running in the backgroud of the computer ,and it can only start it after closing all its programs in the background of the computer,buut after few mins,it automatically close again and again , i use the latest version,dose anyone know how to deal with it,i even dont want open it again :(

**Comment by aronCiucu** [comment]
Hello, are you able to reproduce the issue consistently or it happens from time to time? I am trying to find out what triggers it

**Comment by aronCiucu** [comment]
If this issue still exists in the latest version, please reopen
