### ISSUE TITLE
FR - UH60 support

### ISSUE THREAD

**Issue by shearn89** [aronCiucu/DCSTheWay#128]
Hi, would be cool to be able to use this to input waypoints in the UH60 mod. Mod has bindings for all the relevant data entry functions so hopefully not too bad.

If I get time I'll try to take a look myself.

**Comment by blueberrypi-studio** [comment]
From my experience with the way and modded aircraft. They don't mix to well, to be honest I didn't even know you could make waypoints in that lol. Might have a look later

**Comment by shearn89** [comment]
I keep meaning to try this! Am I right in thinking I would need to copy something like the class for the AH64 under the moduleCommands folder, and then update it to show the tool how to interface with the aircraft?

For the UH60 it's just going to one setting on the DGNS, then hitting a bunch of keypad buttons. Very similar to the Apache, although each letter is 2 key presses because of the keypad.

**Comment by blueberrypi-studio** [comment]
If it has keybinds in the settings, you'll be able to do it. A few tips, try and find something that is a fixed point to start from, which can be accessed from anywhere, this will reduce the number of menus needed before transfer. 

If you don't know how to find the relevant codes for buttons let me know and I'll help ya

**Comment by blueberrypi-studio** [comment]
> Am I right in thinking I would need to copy something like the class for the AH64 under the moduleCommands folder

Don't copy the file, but copy the format, I believe there's a few other files that need to be changed (again not at my PC rn but generally keen to help 😄)

**Comment by shearn89** [comment]
Awesome, thank you! I'm away today but should have some time this weekend to take a look.

**Comment by shearn89** [comment]
All done, ready for merging! I couldn't find a way to read /from/ DCS in order to tell what waypoint the system is on, so I've made some assumptions... But it works at least!

**Comment by blueberrypi-studio** [comment]
Nice dude, I had a look last night, and quickly realised I have no idea how waypoints work in the UH-60 lol

There's no way to read what waypoint you are on unfortunately, so assumptions need to be made. Are there any modes which will stop it from working? Or does it work from whichever mode you are in

**Comment by shearn89** [comment]
Ah, they're not too bad! It's a fun module to fly, especially on a server with CTLD enabled!

Okay - at the moment it always increments before adding, so it just overwrites the next X waypoints from whatever you start in when switching to WPT input.

Should work in all modes, the Mode and Display buttons are rotaries on that device in the cockpit, so it just sets them to LAT/LONG and TGR/WPT (for waypoint entry), then goes from there.

I realised I didn't code up the " " character, as I think that's supported in names. I'll take a look tomorrow if I can, just need to remember which key it is!

**Comment by shearn89** [comment]
I added in the special characters and the alert as mentioned on the PR. I think this is now ready for review + merge.

**Comment by shearn89** [comment]
🥳
