### ISSUE TITLE
New project request: Countermeasure program automatic input

### ISSUE THREAD

**Issue by Shimakaze514** [aronCiucu/DCSTheWay#129]
After ED banned modification in Cockpit/Scripts folder, any edit for countermeasure config file will not pass the IC. Therefore, one must manually push the buttons in the cockpit everytime entering a new slot if they want to edit the countermeasure program.
As the principle of automatic entering waypoints is the same to automatic entering the countermeasure program (which is all "pushing the buttons in the cockpit), is it possible to create a new program based on DCSTheWay to save time and effort for players to edit countermeasure program? If you can start a program on this, it will be a pleasure for many players

**Comment by blueberrypi-studio** [comment]
Have you seen DCS-DTC, it might have what you're after

**Comment by aronCiucu** [comment]
Hi, this is a fine idea, if I find the spare time I might consider this, but for now, use existing programs which do that (DCS DTC is based upon TheWay code for inputs anyway)
