### ISSUE TITLE
Remove from always on top

### ISSUE THREAD

**Issue by Backspacegun** [aronCiucu/DCSTheWay#132]
Is there anyway to stop the program from always being ontop?
Currently my second screen is full of stuff & programs needed for DCS, but TheWay is the only one that is forced to be always ontop of everything else, meaning that if i want to open something infront of it i need to minimise it everytime and reopen it if i want to make changes.

**Comment by aronCiucu** [comment]
Hi, the program is always on top so that when you click on the F10 map and drag on it, the interface is still shown on screen, otherwise you will need to alt tab every time you wanted to save a waypoint. Hence why it's this way

**Comment by aronCiucu** [comment]
Feature will be added with the next release
