### ISSUE TITLE
Ka-50 II and III waypoint transfer

### ISSUE THREAD

**Issue by bitfoxzero** [aronCiucu/DCSTheWay#136]
v2.3.0 - Tested in both II and III modules for non-VR - v2.9 (I don't think it was working for previous 2.8 version either) 

- Selected 3 waypoints on Caucasus SP cold start mission with different LAT LONG ranges
- Result is always the same: Only 1 waypoint is created and the LAT LONG is incorrect and# 6 fixated: ex. 66'00.6 000'30.6 and 66'00'6 065'05'0 there is some variance but generally the 6 key is used often and when there are no 6's in the original LAT LONG

If app uses keybindings for input, both modules are using the same standard keyboard settings (RALT + #). Possibly a user error but I don't see custom instructions for the Ka-50 like the F/A-18.

Validated both the .LUA and did a fresh update prior to testing.

**Comment by JCalebBR** [comment]
Can confirm it doesn't work for me as well

**Comment by aronCiucu** [comment]
Weird, could you also attach a video so I can better see it in action?

**Comment by bitfoxzero** [comment]
https://github.com/aronCiucu/DCSTheWay/assets/101195444/d91beb41-5790-4ce2-8fc4-0dfaa53750e0

See attached, quality is low due to 10mb file limit. This was tested on Instant Action > Ka-50 III > Runway Takeoff > Caucasus. Previous tests were done with Multithread version, this test was done on non-MT - getting same results on both.

**Comment by aronCiucu** [comment]
Thanks, the issue has been spotted and a fix will be out for the next release
