### ISSUE TITLE
Coordinate Transfer F-16

### ISSUE THREAD

**Issue by spec10** [aronCiucu/DCSTheWay#138]
it seems like one of the current updates (OB 2.9.0.47168) broke something. When I try transferring coordinates in the F-16 I can see the transfer macro going dobber down twice then trying to enter the N/S coordinate, but the ded at that point will be at the input field for W/E already with dobber down twice, so it does not work.

**Comment by aronCiucu** [comment]
Hi, could you please attach a video of the issue?

**Comment by aronCiucu** [comment]
@spec10 please try the latest version of the program, and reopen the issue if it persists
