### ISSUE TITLE
I get a "No connection to DCS" error!

### ISSUE THREAD

**Issue by J0KER0612** [aronCiucu/DCSTheWay#143]
Hi mate,
I downloaded The Way since 2.3.0; it runs perfectly, but since I updated it to 2.3.1, I cannot use it in online mode, even though the sever has already enabled player export. I tried to totally delate and reinstall it, but it still cannot work for online but single player. I rechecked the scripts folder, and everything is where it should be. Could you please help me solve this problem?

**Comment by J0KER0612** [comment]
here is how my export.lua looks like 
<img width="891" alt="image" src="https://github.com/aronCiucu/DCSTheWay/assets/105374603/9778722b-fa70-4aa8-9395-df46d70730a2">

**Comment by aronCiucu** [comment]
Hello, have you also placed the folder TheWay that you got from the zip file, next to the Export.lua? Can you also share your dcs log file?

**Comment by aronCiucu** [comment]
Could you drag and drop the entire log file here?

**Comment by J0KER0612** [comment]
> Could you drag and drop the entire log file here?

**Comment by J0KER0612** [comment]
[dcs.log](https://github.com/aronCiucu/DCSTheWay/files/13551829/dcs.log)


> Could you drag and drop the entire log file here?

**Comment by aronCiucu** [comment]
Could you temporarily remove the iUFC lines in the Export.lua, to see of that interferes with TheWay?

**Comment by J0KER0612** [comment]
The way works online now, but is there anyway I can use iUFC an the way at same time

**Comment by J0KER0612** [comment]
> Judging by the log files it appears that this iUFC mod is interfering with TheWay and not letting it use the TCP connection it requires, I'm not really sure how to fix this since the iUFC code is not under my control...

ok thanks pretty much mate
