### ISSUE TITLE
Performance issue on complex multiplayer servers?

### ISSUE THREAD

**Issue by dapendragon** [aronCiucu/DCSTheWay#146]
When trying to join Grayflag's server Sinai/Marianas (running server 2.9.2.49940) the UI such as the select role screen becomes really slow or freezes entirely. If I wait for 3-4 minutes per UI interaction and actually get into a cockpit the game seems to catch up again, but opening any menu, even the basic "escape" menu reintroduces the issue. I've seen similar issues on other servers with complex missions as well, but never this extreme.

It seems very similar to what happens when too much work is performed in the UI thread, and I do get messages from Windows saying DCS is frozen. 

If I remove the supporting script from Export.lua I'm able to join as normal. Grayflag Sinai has a _lot_ of available player slots: 500 Apache slots, 1000+ Mi-8 slots and assorted others. Maybe there's an issue with the slot detection code when faced with these kinds of numbers, I'm not sure.

**Comment by aronCiucu** [comment]
Hello, could you send me a video of the issue happening? Because I tried doing the same on Grayflag Syria and I had no issues navigating the UI

**Comment by dapendragon** [comment]
Hi, thanks for following up! 

I'm having inconsistent results regarding this, and the main server I always have issues with is Enigmas Cold War server, whereas on Grayflag it seems dependent on the number of people on, phases of the moon or something, it's weird. :) 
If you can be bothered to try the Enigma sever, it'd be interesting to see, but I'm starting to suspect it's the combination of some specific features with busy ground wars and/or scripting in missions and potentially bugs in DCS. Probably in conjunction with a specific hardware/config combination.

**Comment by aronCiucu** [comment]
Interesting, I tried Engima and I had no problems navigating the menus... What PC specs are you running?

**Comment by aronCiucu** [comment]
@dapendragon

**Comment by dapendragon** [comment]
Ryzen 9 5900X, 64 GB RAM, Nvidia 3080. I'm able to consistently reproduce this this on Enigma without TheWay loaded, so it's probably something else. The findings on GrayFlag are interesting though - it may be a separate issue where TheWay possibly plays a role, but it's likely being masked by what I'm seeing on Enigma. I suggest we close this one for now. 

Thanks for following up though!
