### ISSUE TITLE
No Connection to DCS

### ISSUE THREAD

**Issue by CrazyPotatoes** [aronCiucu/DCSTheWay#148]
Not sure what's going on here.

DCS.exe is listening to port 42070
  "TCP    127.0.0.1:42070        0.0.0.0:0              LISTENING       4324"
Ensured firewall isn't blocking the app or restricting it. Added it to the list of permissions.

TheWay.lua is in the scripts folder. It's the latest version.

My export.lua is correctly loading the file.
The log file says it's initialized and loaded but has errors, line 107 of TheWay.lua, tcpServer is nil.

Made a modification to TheWay.lua around line 107 by injecting:
```
        if not tcpServer then
            log.write("THEWAY", log.ERROR, "tcpServer is not initialized")
            return
        end
```
This resulted in the log file having tcpServer is not Initialized spam. Redundant check I guess.
I removed all the network initializations from the export lua start function and placed them in the global space for that file. This removed the error, so I guess it means it executes that function now.

However it still doesn't work, so I tried some sniffing. DCS is pumping out a bunch of JSON data on ports designated by DTC and SRS, but nothing out of 42069 udp. This is very strange, because your LuaExportAfterNextFrame() has no breaks but has an interestingly written if that sends "toSend" message on udp 42069. But, this message never shows up on the sniffer and TheWay app always reports no connection to DCS. I tried a different approach:

    local status, err = pcall(function()
        udpSpeaker:sendto(toSend, "127.0.0.1", 42069)
    end)
    if not status then
        log.write("THEWAY", log.ERROR, "Unable to send data: " .. tostring(err))
    end

But this didn't make a difference.
I tried adding a debug line to it:
log.write("THEWAY", log.INFO, model)
to send model to the log file after it grabs selfData.Name or 'Spectator', however nothing shows up in the log. This tells me LuaExportAfterNextFrame() is never being called?

Any ideas?

**Comment by CrazyPotatoes** [comment]
Seems at this point there is a new error too
Saved Games\DCS.openbeta\Scripts/TheWay.lua"]:51: attempt to index upvalue 'crosshair' (a nil value)

Line 51:
```
function LuaExportStop()
    crosshair:setVisible(false)
end
```
crosshair is also defined in LuaExportStart()
```
crosshair = DialogLoader.spawnDialogFromFile(
        lfs.writedir() .. "Scripts\\TheWay\\Crosshair.dlg"
    )
```
But the file exists.

So, what is happening to these functions? Hold on. I think I just realized they are global functions. Oh boy...

**Comment by aronCiucu** [comment]
Hello, could you send me a screenshot of the contents of your Export folder?

**Comment by CrazyPotatoes** [comment]
Supposedly dofile prevents the global functions from overwriting each other and creates their own instance of each function. I have 4 scripts in there, other than yours, that all do the same thing. They define a global function such as exportAfterNextFrame(), but they all do their job without issue.

![image](https://github.com/aronCiucu/DCSTheWay/assets/13650907/03d7b125-c2f5-4505-b526-7d62c8294feb)

And the entire contents of my export.lua minus comments:
```
local TheWayLfs=require('lfs'); dofile(TheWayLfs.writedir()..'Scripts/TheWay.lua')
local Tacviewlfs=require('lfs');dofile(Tacviewlfs.writedir()..'Scripts/TacviewGameExport.lua')
local Fulfs=require('lfs');dofile(Fulfs.writedir()..'Scripts/FuScript.lua')
local DCSDTClfs=require('lfs'); dofile(DCSDTClfs.writedir()..'Scripts/DCSDTC.lua')

pcall(function() local dcsSr=require('lfs');dofile(dcsSr.writedir()..[[Mods\Services\DCS-SRS\Scripts\DCS-SimpleRadioStandalone.lua]]); end,nil)

```
Interesting that SRS uses pcall here, as despite the errors I saw from TheWay.lua, those errors did not seem to affect the functionality of the other files.

**Comment by CrazyPotatoes** [comment]
Yes both in multiplayer and singleplayer. I've been loading into an F-16C to test.

**Comment by CrazyPotatoes** [comment]
Ok, I have found the problem through isolation. It seems the functions are chained together and one of the other scripts did not incorporate this method. I've repaired it copying the method and it works now.

My apologies for wasting some of your time. It seems there was no problem with your script.

**Comment by aronCiucu** [comment]
I see, now I'm considering implementing the pcall method as well
