### ISSUE TITLE
The way stops working once game is moved to new drive

### ISSUE THREAD

**Issue by Slick-1** [aronCiucu/DCSTheWay#152]
I moved dcs to a new ssd and the way stopped working. Is there a way to change a directory to get the connection back?

**Comment by aronCiucu** [comment]
Hello @Slick-1 , make sure the new game location has all the needed scripts as outlined in the instructions, if it does then everything should work

**Comment by Slick-1** [comment]
Instructions have been followed.  I updated the export.lua file per the instructions just to make sure I did it right.  I hit transfer and nothing happens.  I can read the coordinates in but it doesn't put them into the airplane.  Are there any files I need to copy over from the default installer? Is there an error log I can pull that might be useful?

**Comment by aronCiucu** [comment]
Send me your dcs.log file from Saved Games/Logs

**Comment by Slick-1** [comment]
[dcs.log](https://github.com/aronCiucu/DCSTheWay/files/14157570/dcs.log)

**Comment by aronCiucu** [comment]
Could you try to comment out all the other lines in Export.lua besides the one for TheWay? I am seeing some errors in the logs which belong to other scripts which may interfere

**Comment by aronCiucu** [comment]
TheWay seems to be loaded correctly. How are you testing this, inside an instant action mission?

**Comment by Slick-1** [comment]
tested on instant action and Grayflag

**Comment by Slick-1** [comment]
Dunno if this is helpful but I removed all the mods I was not using and it still doesn't work. Also tried to grab some wireshark data but I wasn't sure what I was looking for so I did not include it. 

[dcs.log](https://github.com/aronCiucu/DCSTheWay/files/14332599/dcs.log)

**Comment by Slick-1** [comment]
Just out of curiosity I moved the game (in steam) back to the original drive but still nothing. 
[dcs.log](https://github.com/aronCiucu/DCSTheWay/files/14334272/dcs.log)

**Comment by aronCiucu** [comment]
So it seems to me from the logs that DCS registers TheWay correctly, however there is an error im another script you have installed which prevents TheWay from functioning right. Try and remove it or temporarily disable it, I have attached a picture with the location of fhe script where the error is coming from 
![Uploading Screenshot_20240219_174722_QuickEdit.jpg…]()

**Comment by Slick-1** [comment]
[Export.lua.txt](https://github.com/aronCiucu/DCSTheWay/files/14367719/Export.lua.txt)
[dcs.log](https://github.com/aronCiucu/DCSTheWay/files/14367725/dcs.log)
gave that a go. I completely deleted the pw-dev_script from the folder not sure where else to delete it from. Also included the log. I'm wondering if that script changed a default setting on me?

**Comment by aronCiucu** [comment]
Could you send me a screenshot of the contents of your Scripts folder?

**Comment by Slick-1** [comment]
Hope this helps. 
![image](https://github.com/aronCiucu/DCSTheWay/assets/157852036/8e1e3b65-ffc9-4519-8077-543a0a5adaf0)

![image](https://github.com/aronCiucu/DCSTheWay/assets/157852036/81e3a699-ba11-47f8-beb9-bd5f4e3fda16)

**Comment by aronCiucu** [comment]
@Slick-1 I think I know ehat the problem is, you have indeed the correct folders in your Scripts, but yout Export.lua file is using an old line for TheWay. Check the install instructions and replace that line with the new one.

**Comment by Slick-1** [comment]
Success.  Thanks so much for all your help.  Is there a donation link? Much appreciated :)
