### ISSUE TITLE
No Connection to DCS after 2.9 update

### ISSUE THREAD

**Issue by BCush83** [aronCiucu/DCSTheWay#157]
Looks like the directory structure changed.  Any way to get it working again? Or is it just me?

**Comment by blueberrypi-studio** [comment]
Just you. The app is still functioning

Only change was restructuring the folder structure of the way files, details for which were included in the install instructions for version 2.4 IIRC

**Comment by BCush83** [comment]
> Just you. The app is still functioning
> 
> Only change was restructuring the folder structure of the way files, details for which were included in the install instructions for version 2.4 IIRC

ooof, even using the mt exe?  I have the folder in scripts and did the export.lua line.  Nothing. :(

**Comment by blueberrypi-studio** [comment]
Yep, single thread or multi won't impact the application, or any other mod you have 

You won't have it setup properly

So:
* Make sure you have the latest version 
* Make sure you added the folder to your scripts folder, **and it's not doubled up inside another folder**
Edit the export.lua with the correct line from the install instructions 

Should look like 
`scripts/TheWay/TheWay.lua` etc and other files

**Comment by Lber657** [comment]
Does "the way" only run on DCS servers and not the stand alone version?

**Comment by Rezzemy** [comment]
The way runs on your computer, not on the server. You can use it in single player and in any multiplayer server :D standalone or steam version as well.

**Comment by Cxn1234567** [comment]
im having the same problem ive made sure things are correct 10+ times its quite frustrating at this point

**Comment by blueberrypi-studio** [comment]
> im having the same problem ive made sure things are correct 10+ times its quite frustrating at this point

Only thing I can say is you can't be correct, because it's not working

Post your DCS.log and verify the line of code in export.lua, and the folder `TheWay` in your scripts folder

If that still doesn't work, join my discord, we offer unofficial support for TheWay, ping @hayds_93 and I'll help you out more

https://discord.com/invite/yJfbDBtz
