### ISSUE TITLE
F/A-18 does not input full coordinates.

### ISSUE THREAD

**Issue by CrazyPotatoes** [aronCiucu/DCSTheWay#158]
If for example, the coordinate taken from the map is  N 14.08.0452, THEWAY only attempts the key presses N 1408 and skips the 04 resulting in an input error. The same for W 145.11.08.0452, it will only enter W 14511 and skip the 04. I made sure with the key press timing set to max time.

**Comment by blueberrypi-studio** [comment]
Do you have the precise waypoint mode active on the hornet like the popup says?

**Comment by CrazyPotatoes** [comment]
There is no popup.

**Comment by CrazyPotatoes** [comment]
That must be the case then, thanks. I might then suggest the feature and a comment on the readme page. I can see how you did it in the js file with firstLat and last4Lat loops, but I'm kinda clueless about modifying the interface to add a conditional checkbox

**Comment by blueberrypi-studio** [comment]
There's a function that's pretty much plug and play, but I'm not sure why you wouldn't want precise coords... It's been over a year since I wrote code for the strike eagle, but there's a 2 options dialogue function somewhere that may be what you want

**Comment by CrazyPotatoes** [comment]
Because it requires switching modes, and to a mode that wasn't typically used on that bloc due to poor state estimation accuracy with GPS. It might be precise to a foot, but inaccurate by tens of meters. It's not an accuracy you'd count on anyways so you'd always be using the standard DDMMSS format and then refining it with a TGP handoff, so that any temporary drift in your state would transfer to the JDAM and be accounted for.

**Comment by aronCiucu** [comment]
Currently all Hornet points are entered as precise, and it will probably remain as such for the future
