### ISSUE TITLE
Where is the "exe"

### ISSUE THREAD

**Issue by DaiERenDaiFaShi** [aronCiucu/DCSTheWay#16]
just as title,I can not find the "TheWay.exe" in the rar,Please tall me where is it,thx

**Comment by aronCiucu** [comment]
Hello, please head over to the latest release (https://github.com/aronCiucu/DCSTheWay/releases/tag/v1.4.0) and click on the TheWayV140.zip file to download it. There you will find the .exe file, and you can further follow the install instructions. 
![image](https://user-images.githubusercontent.com/45103765/147644999-3b4dadd1-881e-420a-89fa-4cc6fe55d2cb.png)
