### ISSUE TITLE
No Connection to DCS

### ISSUE THREAD

**Issue by neverdone77** [aronCiucu/DCSTheWay#162]
I have tried installing several times to no avail. No matter what server or solo session I attempt to join or the module i chose it just says no connection? Any advice? Attached is my folder layout and my Lua File.
![DCS Scripts](https://github.com/aronCiucu/DCSTheWay/assets/173102025/625c9a59-7a63-4847-bbdc-b07c5248f805)
![LUA](https://github.com/aronCiucu/DCSTheWay/assets/173102025/d444de2d-a195-4c81-b328-131d3464f256)

**Comment by blueberrypi-studio** [comment]
Open that "The way" folder and make sure there isn't a doubled up folder in there

**Comment by neverdone77** [comment]
Thank you for the quick response. You can see from the attached here no double folder. 
![They Way](https://github.com/aronCiucu/DCSTheWay/assets/173102025/0cea62ab-52ee-4c51-9cd6-a8356dd4abc4)

**Comment by blueberrypi-studio** [comment]
Did you have DCS open when you installed it/have you restarted DCS since

Is that saved games folder actually being used by DCS? That would be my last guess as to what's wrong (potentially do you have one called DCS.openbeta)

Your install setup looks fine to me other than those two questions 

Put your DCS.log file in here, and I'll take a look (`savedgames/DCS/logs/dcs.log`)

Hopefully @aronCiucu can take a look too, usually when this happens people didn't read the instructions 😅

**Comment by neverdone77** [comment]
[dcs.log](https://github.com/user-attachments/files/15877067/dcs.log)

I do not have an open Beta folder that I can find. 
DCS was closed during install.
I have restarted PC and program to no avail.

**Comment by neverdone77** [comment]
Tried again today with no luck. I'm sure it's something stupid but I can't seem to figure it out.

**Comment by Smi13y01** [comment]
have you had any luck with this? I have the same issue and followed the same method

**Comment by neverdone77** [comment]
Nope still stuck.

**Comment by aronCiucu** [comment]
@neverdone77 Try to edit the Export.lua file and temporarily remove any other lines except the one for TheWay, then save and try again. (Back it up beforehand) If it's not working still, send the log and the export file again so i can check

**Comment by Smi13y01** [comment]
the command line being added to Export lua looks like it's referencing a TheWay lua in the 'TheWay' folder that is now in the Scripts folder but that file does not exist. Could this be an issue?

**Comment by Smi13y01** [comment]
yeah when i followed the directions. i copied the folder with the installation exe to the script folder then launched it and it installed TheWay to \AppData\Local\Programs\theway . this left the 'TheWay' folder in my scripts folder still empty aside from the install exe. sorry @neverdone77 I dont/didnt mean to jump in on your support request

**Comment by neverdone77** [comment]
All good brother. We are all trying to get it to work lol

**Comment by neverdone77** [comment]
@aronCiucu that worked. Removing the other lines from the LUA worked

**Comment by Smi13y01** [comment]
@neverdone77 did you have theway.lau in your folder?

**Comment by aronCiucu** [comment]
> @aronCiucu that worked. Removing the other lines from the LUA worked MY SRS is jacked up now. Reinstalling it to see if it will all jive now

SRS probably doesn't interfere, maybe it's the Winwing export that's the issue. Try to add them back one by one and see what works
