### ISSUE TITLE
No connection to DCS

### ISSUE THREAD

**Issue by VladTheSedater** [aronCiucu/DCSTheWay#163]
I've seen others have had the same issue. Happened after I did a fresh install of the game. Here is my folder as an image. I've tried uninstalling the way with Revo and reinstalling incase it was lookignf or my old install too. Nothing.

![image](https://github.com/aronCiucu/DCSTheWay/assets/173397206/c1947a16-87ac-4e71-a797-6fc9ca572ca6)

**Comment by aronCiucu** [comment]
Hello, please send your dcs.log and the Export.lua file
