### ISSUE TITLE
F-16, tries to enter all waypoint data into LON. Skips LAT

### ISSUE THREAD

**Issue by CrazyPotatoes** [aronCiucu/DCSTheWay#164]
There must have been something in a patch recently that caused a problem? I tried uploading waypoints on the 16 while flying PG and it skiped the LAT and tried to pack everything into the LON. I tried a slower timing and resetting DCS but it still does the same.

**Comment by blueberrypi-studio** [comment]
I'll have a look at this when I get home, I tested it after the Kiowa update and it worked fine for me 😅

**Comment by aronCiucu** [comment]
@CrazyPotatoes make sure to not have selected in the jet a waypoint number above 25 or it starts treating those as markpoints, and the entry process does not work. try from the 1st waypoint at it should work

**Comment by CrazyPotatoes** [comment]
I was trying to input to waypoint 32 I think. Can that be fixed?

**Comment by aronCiucu** [comment]
Not really, only fix is to make sure your jet doesn't have a high steerpoint number already selected,  before transferring

**Comment by CrazyPotatoes** [comment]
I was just trying to look through the code and understand it. I don't see anything about changing press orders above 25 so does that mean the F-16 itself requires a different key order above 25 thus requiring a draw argument to know whether or not it's that high?

**Comment by aronCiucu** [comment]
Yes, the F-16 waypoint Input is different above 25

**Comment by CrazyPotatoes** [comment]
Well I dug as hard as I could through all the devices an other export functions and couldn't find anything that offers that value. That's unfortunate because it's not uncommon for missions or multiplayer environments to have all those steerpoints filled and there isn't a whole lot of use for this beyond the purpose of markpoints themselves.

**Comment by aronCiucu** [comment]
That value is within the F-16 source code, and how the F-16 currently works. If the goal is to enter markpoints the F-16 already provides many ways to do it (HMCS, TGP, HUD, HSD, coords). The purpose of TheWay is not to replace existing F-16 functionality, but to fill in the gap for a waypoints DTC being already loaded before the mission start.

**Comment by CrazyPotatoes** [comment]
I don't know what you mean by this. I never said anything about HMCS, TGP, HUD, or HSD. TheWay replaces manual coord entry from the f10 map with automated entry. When forced to choose, you chose a range of steerpoints that is typically handled by the ME instead of a much much larger range that is typically free.

**Comment by aronCiucu** [comment]
Think of it like this: the DCS F-16 only supports waypoints to be entered in the range of 1-25. Yhis is how ED modelled the F-16. And in order for TheWay to work, when you transfer the steerpoints it needs to fit in that range, otherwise it breaks.
