### ISSUE TITLE
No Connection

### ISSUE THREAD

**Issue by ocgadmin** [aronCiucu/DCSTheWay#173]
Have uninstalled and reinstalled (v2.5) still no connection to DCS

Cheers
Hells

**Comment by blueberrypi-studio** [comment]
Make sure you have followed the install steps correctly, including the `export.lua` line of code, and make sure the folder in your saved games is correct `C:\Users\xxxx\Saved Games\DCS\Scripts\TheWay` should have 3 files in it

**Comment by ocgadmin** [comment]
Thanks for the reply. There seemed to be a problem with my Saved Games.  Removed and rebuild fixed the problem.

Just need to add the CH-47F if possible
Cheers 
Hells

**Comment by blueberrypi-studio** [comment]
Been working on the Chinook, it's proving difficult, DCS doesn't like giving me the info I want to make it work, I'll get it eventually 😅

**Comment by ocgadmin** [comment]
Look forward to it
