### ISSUE TITLE
Elevation follows the map?

### ISSUE THREAD

**Issue by momcilo78** [aronCiucu/DCSTheWay#18]
Are we really supposed to use the waypoints with elevation set exactly to the same value and terrain?
I would expect to be able to elevate the waypoint above the groum.

**Comment by aronCiucu** [comment]
Hello, currently the waypoints take their elevation from the point on the map you selected.

**Comment by Jeffb4u** [comment]
Simply select the WP in the HSI/Data page and UFC the elevation like you would any waypoint for flyover altitudes - if your marking tgts on the ground to Kill then you need the waypoint as it is so why change it....... no need to add bells and whistles...
