### ISSUE TITLE
大佬你好

### ISSUE THREAD

**Issue by Jinny-114** [aronCiucu/DCSTheWay#19]
我有几个建议：
1，Java的运行环境能不能设置成允许用户自定义，而无需捆绑下载自带的运行环境——须知用到Java运行环境的用户也不算少
2，希望增加各种机型各种武器输入PP模式坐标的功能，对于多目标攻击来说，这将更加得心应手
如果能采纳我的建议，将不胜荣幸！

**Comment by aronCiucu** [comment]
Hi, the latest version does not require Java anymore
