### ISSUE TITLE
Option to not discard points on entry

### ISSUE THREAD

**Issue by andrey-bolduzev** [aronCiucu/DCSTheWay#2]
Something I've noticed using the latest version is that the selected points are automatically discarded when entered into the aircraft. In the tutorial video though it looks like the points survive and can be entered again without selecting them on the map. The latter variant is convenient for being able to respawn and re-use the same points. I wonder if this functionality could be brought back in some form?

Thank you for the awesome tool!

**Comment by aronCiucu** [comment]
Hello, I'm really sorry for the late reply, I've been caught up with things all these days... I'll definetly add this to be considered, as I too happened to have to redo the same flight and have to select my waypoints again... Thanks for the suggestion!
