### ISSUE TITLE
When Inputting coordinates, Error on F/A-18 UFC,  only Elevation is being entered correctly  the rest is 0 

### ISSUE THREAD

**Issue by Jpatty54** [aronCiucu/DCSTheWay#20]

**Comment by Jpatty54** [comment]
it will work on a current mission, but an older mission won't work.  so it's ok

**Comment by Phrown420** [comment]
I'm having this issue too in the f-18, created new missions to test it out and no matter what I do the first waypoint only gets its elevation entered but no coordinates. Running v151 (the latest). I've made sure I'm not in the TAC menu, I have boxed precise, and I have the right format selected.
