### ISSUE TITLE
F-18C HSI Issues:

### ISSUE THREAD

**Issue by jasonmayr** [aronCiucu/DCSTheWay#22]
I noticed that the waypoint data (i.e.. Lat and Long, alt, etc.) is inputted, but the Sequence is not inputted. so there are waypoint data, but no 1, 2, 3, 4, etc. to follow. And to work around just manually enter the sequence, and you can follow the date in flight. but if there's no sequence data. all you have is 1 waypoint 0, and no other points to follow. If the software is working right, not only would the Lat & long data be added, but the points that data is assigned to as well.

**Comment by aronCiucu** [comment]
Hello, I would take this suggestion of yours to implement the route in the future, as currently I do not own the Hornet and was using the free trial to make it work.
