### ISSUE TITLE
Apache Relates issues!

### ISSUE THREAD

**Issue by jasonmayr** [aronCiucu/DCSTheWay#23]
It sometimes works and sometimes not. But regardless it only enters 2 points and then the seems to be a issue.

**Comment by aronCiucu** [comment]
Hello, currently I am aware of issues with high framerates (above 60, ude Vsync to mitigate that) and multiplayer where the waypoints are entered by the CPG (let the pilot enter the waypoints to mitigate the issue). If your problem is different to the scenarios above, feel free to send me a video with the issue happening so I can debug it further.

**Comment by aronCiucu** [comment]
Weird, from what I see in the video it appears that 6 waypoints are entered into the helicopter at the beginning, I will try to replicate the issue as soon as I can, but for now I cannot really spot it....

**Comment by jasonmayr** [comment]
Yes it does but it enters what I think is a edit of the last waypoint and keeps  inputting   . 

Jason
904-335-7803
Sent from my iPhone

CONFIDENTIALITY NOTICE: This e-mail message including attachments, if any, is intended for the person or entity to which it is addressed and may contain confidential and/or privileged material. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail and destroy all copies of the original message. Thank you.

**Comment by aronCiucu** [comment]
Check if everything is working now after the latest update

**Comment by jasonmayr** [comment]
This was in single player. I entered 4 waypoints and the first 2 entered, but the last 2 didn’t. It got stuck some where in the upload. 

Jason
904-335-7803
Sent from my iPhone

CONFIDENTIALITY NOTICE: This e-mail message including attachments, if any, is intended for the person or entity to which it is addressed and may contain confidential and/or privileged material. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail and destroy all copies of the original message. Thank you.

**Comment by jasonmayr** [comment]
working perfectlyOn Mar 31, 2022, at 11:13 AM, Aaron Daniel ***@***.***> wrote:Check if everything is working now after the latest update—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
