### ISSUE TITLE
NS430 support

### ISSUE THREAD

**Issue by Floydii** [aronCiucu/DCSTheWay#29]
Is it possible to add NS430 support? Using X1,X2,X3 etc as the waypoints. Far easier than twiddling the NS430s dials yourself :).

**Comment by Wamwod** [comment]
This probably isn't what you want but if you get the DD (Degree Decimal) of the waypoint you want you can edit the navaids.dat and give it a name like ex. `01` `02` `03` and make a flight plan through there. DCS Scratchpad has similar functionality similar to what your looking for with a PR https://github.com/rkusa/dcs-scratchpad/pull/27 until they respond to this feature request.

**Comment by aronCiucu** [comment]
Hi, unfortunately I am not familiar with the NS430 system nor do I own the module, if there is anyone having experience with it, I am encouraging them to contribute to the code with that feature, otherwise, it's unlikely I could add that support myself
