### ISSUE TITLE
Multiple monitors

### ISSUE THREAD

**Issue by EltonAA** [aronCiucu/DCSTheWay#3]
Hello friend,

I love your waypoint tool! Though, I use multiple monitors when flying in DCS. When going into the F10 map, DCS places the map only into the center monitor while your pink pointer dot remains static in the left monitor. Do you have a current work around for this?

I will post a photo of my desktop...

Thanks,
Elton

![IMG_6002](https://user-images.githubusercontent.com/86527527/123518393-89122300-d65a-11eb-99f9-8f1bf4248b58.jpg)

**Comment by aronCiucu** [comment]
Hello, sorry for the late reply, been a bit busy these days... Hmm, really confusing as I use multiple monitors as well... Try and launch TheWay from your main monitor, or make the DCS monitor the main one, see if that help... I hope it does

**Comment by Bones1775** [comment]
EltonAA
you can change the GUI in the Monitor setup lua. editing these lines 

UIMainView = Viewports.Left

GU_MAIN_VIEWPORT = Viewports.Left
![20211206_170438](https://user-images.githubusercontent.com/95657759/144931036-fbd322a8-8401-431f-950a-9c5697a32c09.jpg)

**Comment by BlueFinBima** [comment]
I'm a bit late to this party, but one circumvention if you want to keep your DCS and UI different (and I'm not recommending this to anyone) , is to take a sharpie and place a small dot in the center of the screen used for the GUI ;-)

**Comment by aronCiucu** [comment]
Hi, please try out the latest release, if it still doesn't behave as expected, reopen the issue
