### ISSUE TITLE
[FEATURE REQUEST]  WP Export & Import: Automatic JTAC Input: Waypoint Input Types

### ISSUE THREAD

**Issue by ttdsi** [aronCiucu/DCSTheWay#32]
This is an extremely handy tool thank you! But make it more capable!
 
 Waypoint Export & Import- Feasible and 1# thing that should be done, Simply add a text box to the executable with a button that exports & Imports a format containing selected coordinate information that can be highlighted and copied. Enabling users to share that information via other channels (Discord, Ingame chat, ect)
 
 Aircraft WP&TGT Data Export- No Idea how, Extremely Vital, getting WP and or current target point coordinate information to the above textbox. Hotkeys keys for this would be helpful too.

 Automatic JTAC Input- Might be feasible? Semi Vital, To avoid arduous coding, create or use the same text box above to output the coordinate information given by JTAC into the box using the same format, that can then either be copied and shared or imported into your aircraft!
 
 Waypoint Input Types- Might be tedious, Handy, create differing aircraft input sequence types to account for a selected waypoint type. Represented by added buttons to the java GUI, "TGT WP" "NAV WP" "STRP" ect.

**Comment by aronCiucu** [comment]
Hi, the import/export feature was added in the latest release, please check it out. Hotkeys were also implemented
