### ISSUE TITLE
Feature Request: Display in VR

### ISSUE THREAD

**Issue by BCush83** [aronCiucu/DCSTheWay#35]
Using SRS and even scratchpad as an example...can you somehow get it "in game" vs a seperate application so us VR players can utilize this?  Not sure if any code from these projects would be helpful?

https://github.com/rkusa/dcs-scratchpad
https://github.com/ciribob/DCS-SimpleRadioStandalone/releases

But awesome job...love it...just really, really wish it could be used in VR.  Please.

**Comment by kylane** [comment]
+1 for this!

**Comment by blueberrypi-studio** [comment]
you can get this working in VR, you just have to take your headset off and look at the screen mirror on your monitor (since DCS still runs on your monitor), then use the Dot on the screen as normal, Its a workaround, and far from perfect, but it works better than typing all the numbers in yourself

**Comment by IdefixRC** [comment]
+1

and the ability to assign Hot Keys to the 4 commands to we can trigger them with voice commands using Voice Attack

**Comment by aronCiucu** [comment]
Hotkey support was added in the latest release, enjoy
