### ISSUE TITLE
Folder name is seemingly always just DCS, putting script in openbeta does not work

### ISSUE THREAD

**Issue by FlareFlo** [aronCiucu/DCSTheWay#36]
The readme states the following:
> The DCS folder name may be DCS.openbeta if you are on the openbeta version of the game.
After only putting the files there, and launching the OB client, it did not work, whereas using the regular folder does.

**Comment by EpiicPenguin** [comment]
not sure but this could be the issue

if you open dcs through steam, it uses the dcs folder, even if you have downloaded open beta branch through steam, 
only dcs standalone installed separately in its own `.openbeta install` will use the` DCS.Openbeta` folder in saved games. 

to test which folder the game is using : if you have custom skins installed see which `saved game/xxx/liverys `folder they are in, and make sure that they are working. 

i had this problem with my game earlier adding skins and scripts during my migration from steam to standalone, hope this helps.

**Comment by aronCiucu** [comment]
Thanks, will note it down for the README
