### ISSUE TITLE
Proposal: Combine develoment with "DCSWaypointEditor"

### ISSUE THREAD

**Issue by EpiicPenguin** [aronCiucu/DCSTheWay#37]
I just tried "DCS The Way" and DCSWaypointEditor programs and both programs fundamentally do the same thing but in different ways.  The Way's waypoint entry method speed, and being able to capture from the F11 view are amazing features and DCSWE  features like hotkey support, saved waypoint profiles and sequences, PrePlaned jdam and Stations are also incredible. 

I propose that development of DCSWaypointEditor app and the Way might be combined.

If development of the 2 apps could be combined i believe that it would lead to a better app and lighter development load shared and spread around more of the dcs modding community. 

I believe xkcd 927 applies partially here as well, https://xkcd.com/927/

full disclosure  : I am not a programmer and i have have not contributed to either project and i don't know if java vs python would be a major barrier for development, but it seems like something worth considering. 

I love all the work both teams do, and thank you very much for even considering my proposal. 

Penguin.

**Comment by aronCiucu** [comment]
Hi, the latest version includes things from DCS waypoint editor like files and hotkeys. Enjoy!
