### ISSUE TITLE
GUI to just display the coordinate selected 

### ISSUE THREAD

**Issue by Stevegon** [aronCiucu/DCSTheWay#38]
I love this app! Thank you for your excellent work and sharing. I have a request, which I think you'll agree would be cool. Please add an option on the popup GUI to just display the coordinate selected on the F10 map without auto-entery. This way, it gives the option to manually enter the coordinate ( for sadists lol) and have the coordinate handily displayed on the 'always on top' popup screen of the GUI!
Thanks for your consideration!

**Comment by aronCiucu** [comment]
The latest release displays the coordinates you have selected
