### ISSUE TITLE
Feature Request - Upload XLS waypoint list

### ISSUE THREAD

**Issue by rglasinovic** [aronCiucu/DCSTheWay#4]
Hello.
This program is really awesome!
It would be nice to have an upload XLS list feature. Many of us work with a navlog with our squadrons, and If we can use it as a preplan waypoint upload featyre would be great.
Thanks

**Comment by aronCiucu** [comment]
Hello, my apologies for the late reply, these days have been quite stacked for me... Indeed this is a very requested addition, and it's definitely on my todo list for the program. Thanks for your suggestion!

**Comment by aronCiucu** [comment]
Hi, the newest  version supports file input/output
