### ISSUE TITLE
[FEATURE REQUEST] Constant altitude for navigation waypoint

### ISSUE THREAD

**Issue by cubyblue** [aronCiucu/DCSTheWay#43]
Hi Aron, 
 
I have a request for a new feature that might be useful for some aircraft.The idea is to be able to define a fixed altitude with a textbox in the theway application, so that each of the waypoints that will be entered by theway is redefined at the altitude entered by the player.
This would make it possible to make trips for the autopilot of the F18 for example.

Thx in advance, 
cubyblue

**Comment by aronCiucu** [comment]
Added in the latest release, you can now edit the elevation
