### ISSUE TITLE
SOFTWARE JAVA required

### ISSUE THREAD

**Issue by jdam-sfs** [aronCiucu/DCSTheWay#48]
Hello,
To use TheWay in DCS do I need to install the JAVA software on my PC?

Thank you for your reply.

**Comment by poppcapnurass** [comment]
I'm not the Dev but have been using The Way for at least a year.
This time I installed The Way on Win11  Windows Defender gave a message saying Java was required to use it. Since I have Avast Premium running, I dumped Windows Defender and have not been asked for the Java requirement again.

**Comment by ELMEXICO** [comment]
Hi,
i have the same problem und tryed to uninstal the windows Defender and it still says i need JAVA.
PLS send Help.
Thanks

**Comment by aronCiucu** [comment]
Hi, the latest version doesn't need any Java anymore
