### ISSUE TITLE
Shortcut Keys

### ISSUE THREAD

**Issue by Abburo** [aronCiucu/DCSTheWay#5]
Awesome application Daniel!
As a suggestion for further development would be nice to have some configurable shortcut keys which might help with VR usability. We can use macro's then and map wherever on our hotas devices or using directly the keyboard.
Also, A10C would be fantastic to be able to use this app.

Romanian: sunt incantat sa vad ca esti roman iar daca doresti sa stai de vorba si cu altii de ai nostri ne poti gasi pe Guilded aici:
https://www.guilded.gg/i/m24Bz49p

Daca nu doresti sa ni te alaturi iti las macar un link pentru ceva skinuri cu tematica RoAF create de noi:
https://www.guilded.gg/Simulator-World-Romania/groups/1dgl78Az/channels/c98870e5-08d1-4f54-aeab-1d06a73d690d/media

Cele bune,
Abburo

**Comment by aronCiucu** [comment]
Hello, my apologies for the late reply... Keybinds have been in plan for quite a while, but unfortunately it may not be possible as the Windows API does not allow a program which is not in focus to listen for key presses, perhaps for security concerns... I'll try and find out more however, and see if I can somehow make it work... I'll definitely join your community however!

**Comment by aronCiucu** [comment]
Added in the latest version, i managed to find a way for it to work
