### ISSUE TITLE
[FEATURE REQUEST] Support for Black Shark 3 Ka50_3

### ISSUE THREAD

**Issue by Xtrasher** [aronCiucu/DCSTheWay#51]
As in the title. would be cool to get BS3 support too :) looks like it's the same as for the BS2 but elseif is triggering "unsupported modul". copying the Ka50 code and name it Ka50_3 in a second elseif worked for me in debug (looks like, need more testing) but i am to stupid to compile that stuff.

**Comment by atcz** [comment]
It just needs the name added in WaypointManager.java, much like A-10C and A-10C_2

https://github.com/aronCiucu/DCSTheWay/commit/149640c81e11c9adbf6edef8bb4ab49ae0284495

**Comment by GoldJohnKing** [comment]
I have compiled one with Ka-50_3 support, anyone can use this as a temporary solution before [aronCiucu](https://github.com/aronCiucu) releases an official one.

https://github.com/GoldJohnKing/DCSTheWay/releases

**Comment by Xtrasher** [comment]
> 

Cool thank you very much :-) will test it later.

**Comment by kangjiajinlong** [comment]
Hi GoldJohnKing,

Thanks for the fix. I wonder how I can display the point I selected on F10 map in ABRIS. It appears that the point can be entered into PVI-800 but I do not know how to display it in ABRIS. All tutorials I saw online talked about drawing waypoints first in ABRIS and enter them in PVI-800, but none of them talked about how to do it the other way around (if it is ever possible).

**Comment by Xtrasher** [comment]
> Hi GoldJohnKing,
> 
> Thanks for the fix. I wonder how I can display the point I selected on F10 map in ABRIS. It appears that the point can be entered into PVI-800 but I do not know how to display it in ABRIS. All tutorials I saw online talked about drawing waypoints first in ABRIS and enter them in PVI-800, but none of them talked about how to do it the other way around (if it is ever possible).

Yes thats normal you need to add/edit the FPL (Flightplan) on the ABRIS yourself ... Its a while ago so can't tell you how right out of the head ... but it is possible somwhere on the abris to add/edit a waypoints. i learned how to a while back from youtube.  Most times i just use the PVI so ....

**Comment by Xtrasher** [comment]
> > Yes thats normal you need to add/edit the FPL (Flightplan) on the ABRIS yourself ... Its a while ago so can't tell you how right out of the head ... but it is possible somwhere on the abris to add/edit a waypoints. i learned how to a while back from youtube. Most times i just use the PVI so ....
> 
> It seems that there is no way to enter coordinates into ABRIS...

yah could not find it too was sure you could when editing a point, but looks like i its not ... remembered that wrong sorry

**Comment by Xtrasher** [comment]
> > Yes thats normal you need to add/edit the FPL (Flightplan) on the ABRIS yourself ... Its a while ago so can't tell you how right out of the head ... but it is possible somwhere on the abris to add/edit a waypoints. i learned how to a while back from youtube. Most times i just use the PVI so ....
> 
> It seems that there is no way to enter coordinates into ABRIS...

Not waypoint input on abris but you can use NAV TGT on PVI-800 and they will be shown on ABRIS when selected.
https://youtu.be/qv6lzVYQF98?t=140
Maybe that helps a bit.

**Comment by blueberrypi-studio** [comment]
> I have compiled one with Ka-50_3 support, anyone can use this as a temporary solution before [aronCiucu](https://github.com/aronCiucu) releases an official one.
> 
> https://github.com/GoldJohnKing/DCSTheWay/releases

quick question, I'm looking to do a similar thing to add modded support, got it working, but can't compile it into a similar style package, can you advise me on what you did?

cheers

**Comment by TOGGka50lover** [comment]
> It just needs the name added in WaypointManager.java, much like A-10C and A-10C_2
> 
> [149640c](https://github.com/aronCiucu/DCSTheWay/commit/149640c81e11c9adbf6edef8bb4ab49ae0284495)

How do I install it?

**Comment by e-LEMONator** [comment]
> > I have compiled one with Ka-50_3 support, anyone can use this as a temporary solution before [aronCiucu](https://github.com/aronCiucu) releases an official one.
> > https://github.com/GoldJohnKing/DCSTheWay/releases
> 
> quick question, I'm looking to do a similar thing to add modded f16 support, got it working, but can't compile it into a similar style package, can you advise me on what you did?
> 
> cheers

I'm looking to do the same myself. I was going to submit a PR, but wanted to export it so I could test my change on my end.

**Comment by blueberrypi-studio** [comment]
can't remember exactly, but you need maven (a build tool), then you need to add [this ](https://github.com/blueberrypi-studio/DCSTheWay/blob/main/assembly.xml) file. I also think you need a JRE in the folder too so people without java installed can use the app 

(I figured this out from @GoldJohnKing 's branch of the repo)

otherwise, just make a pull request and i can compile changes if you want

**Comment by blueberrypi-studio** [comment]
@e-LEMONator have you been able to test it at all? because you can just run the project (took a bit of fiddling to get working, but I was able to test it in its raw .java from visual studio code to test it)

**Comment by blueberrypi-studio** [comment]
https://github.com/aronCiucu/DCSTheWay/issues/56#issuecomment-1476934794

https://github.com/blueberrypi-studio/DCSTheWay/releases

if you're trying to add support for the KA50, here is my compiled version

**Comment by e-LEMONator** [comment]
Ah! That works. So you just compiled it to be an executable and included the JRE? Hopefully that will get merged into the main branch/release at some point.

**Comment by blueberrypi-studio** [comment]
> Ah! That works. So you just compiled it to be an executable and included the JRE? Hopefully that will get merged into the main branch/release at some point.

Unlikely, the Dev is currently developing a new version, and I believe that will incorporate the new aircraft. but for now this is plenty good enough. if you want to keep up with the development its the same repo, just on a branch called [electron](https://github.com/aronCiucu/DCSTheWay/tree/electron)

**Comment by aronCiucu** [comment]
Added in the newest release
