### ISSUE TITLE
Wrong Coordinates Since Update

### ISSUE THREAD

**Issue by Countdow** [aronCiucu/DCSTheWay#55]
Since the new MT update inputting multiple waypoints into the F18 causes it to enter coordinates to your actual position and will enter however many points you selected (4 for example) 4 times of the same coordinate

**Comment by blueberrypi-studio** [comment]
how wrong does it appear? just a few numbers off or completely random, haven't noticed any issues in the f16

**Comment by Countdow** [comment]
> how wrong does it appear? just a few numbers off or completely random, haven't noticed any issues in the f16

It seems to set the coordinates to my current position or close to it. When I’m selecting points 70mi away

**Comment by ffxpvc** [comment]
Same here coordinates are way off since updat both in ST and MT. can not use it any longer

**Comment by aronCiucu** [comment]
I am currently in the process of rewriting the whole codebase, and all modules will get a check again

**Comment by blueberrypi-studio** [comment]
Hey @aronCiucu glad to see this project is still alive :-). I tested it with the f18 on MT and it worked fine for me, I even grabbed the points in VR, with no issue.

thanks for developing this, It's a lifesaver

-Haydn

PS. can we get some modded support for stuff that overwrites modules (Super Hornet, F16I-SUFA etc)

**Comment by tllegault3830** [comment]
For me  I it gives me an error on the ufc and no waypoint. 
If I copy say 4 waypoints it gives the error for the first waypoint and does the next three fine.

**Comment by aronCiucu** [comment]
Please check the newest release, the Hornet has gotten a review

**Comment by tllegault3830** [comment]
Thank you! I appreciate you hard work!
