### ISSUE TITLE
not working for the KA 50

### ISSUE THREAD

**Issue by TOGGka50lover** [aronCiucu/DCSTheWay#56]
as the title says it doesnt work for the KA 50 I am unsure if its only not working with the BS3 or if that is a generall problem for the KA 50 a fix or adding the BS3 would be nice

**Comment by blueberrypi-studio** [comment]
https://github.com/aronCiucu/DCSTheWay/issues/51#issuecomment-1371795816

someone else has made a release for it, I have also made one for the ka50 and the f16 I sufa mod

https://github.com/blueberrypi-studio/DCSTheWay

**Comment by TOGGka50lover** [comment]
Thanks to the two of you

**Comment by TOGGka50lover** [comment]
> [#51 (comment)](https://github.com/aronCiucu/DCSTheWay/issues/51#issuecomment-1371795816)
> 
> someone else has made a release for it, I have also made one for the ka50 and the f16 I sufa mod
> 
> https://github.com/blueberrypi-studio/DCSTheWay

It doesnt work for the KA 50 Blackshark 3 its important to note that I am talking about the blackshark 3 not 2

**Comment by blueberrypi-studio** [comment]
Hi @TOGGka50lover 

I Don't have the KA50 3, so I can't test this. 
My release of the code [here](https://github.com/blueberrypi-studio/DCSTheWay/releases/tag/v1.5.1.1)
has the relevant changes for you, as shown below
```
else if(model.equals("Ka-50") || model.equals("Ka-50_3"))
```
otherwise, try this [one](https://github.com/GoldJohnKing/DCSTheWay/releases)

both have been compiled into .exe files and can be installed as normal

**Comment by TOGGka50lover** [comment]
> Hi @TOGGka50lover
> 
> I Don't have the KA50 3, so I can't test this. My release of the code [here](https://github.com/blueberrypi-studio/DCSTheWay/releases/tag/v1.5.1.1) has the relevant changes for you, as shown below
> 
> ```java
> else if(model.equals("Ka-50") || model.equals("Ka-50_3"))
> ```
> 
> it has been compiled into s .exe file and can be installed as normal
> 
> -Haydn

Well it enters the waypoints but they dont show on the ABRIS / the big screen on the right
