### ISSUE TITLE
another "No Connection to DCS Detected"

### ISSUE THREAD

**Issue by NorthernSig** [aronCiucu/DCSTheWay#60]
I followed the instructions.  There was no Scripts folder in the location, so I created one and put the modified file into it.  I start .exe prior to starting DCS.  no connection.  I am using the F/A18C.

**Comment by aronCiucu** [comment]
Please be patient until the V2 version launches, it is rewritten from scratch and should hopefully resolve any such issues. You can reopen this issue if it still persists after updating
