### ISSUE TITLE
Feature Request: Ability to change colour of the crosshair

### ISSUE THREAD

**Issue by blueberrypi-studio** [aronCiucu/DCSTheWay#64]
Hiya, I'm somewhat colourblind, so I struggle to see the new cursor, the old purple one was great, is it possible to have a settings option to change the colour of the crosshair/cursor?

also is it possible to add support for the other f16 variants, I haven't been able to modify your code successfully and create a pull request for them, I can make it think they are supported, but then clicking add waypoint does nothing (I am still working on this)  

I tried this in `ConvertModuleWaypoints.js`
```js
const convert = (dcsWaypoints, module) => {
  switch (module) {
    case "F-16C_50":
    case "F-16I" || "F-16D_50" || "F-16D_50_NS" || "F-16D_52" || "F-16D_52_NS" || "F-16D_Barak_30" || "F-16D_Barak_40":
    case "A-10C_2":
    case "A-10C":
    case "M-2000C": {
```

and this in `GetModuleCommands.js`
```js
 switch (module) {
    case "F-16C_50":
    case "F-16I" || "F-16D_50" || "F-16D_50_NS" || "F-16D_52" || "F-16D_52_NS" || "F-16D_Barak_30" || "F-16D_Barak_40": {
      let payload = [
```

and this in `SourceSelector.js`
```js
const supportedModules = [
  "F-16C_50",
  "F-16I", "F-16D_50", "F-16D_50_NS", "F-16D_52", "F-16D_52_NS", "F-16D_Barak_30", "F-16D_Barak_40", //IDM project mods
  "FA-18C_hornet",
```

but Still can't get it to work, I imagine there are more steps buried in the code I am yet to find

cheers

Hayds_93

**Comment by aronCiucu** [comment]
Hello, indeed the corsshair color can be changed, if you clome the repo you will see an image in the public directory called crosshair, that inage can be replaced with any png file to show it as a crosshair. Regarding the other F16 variants, are you sure that they actually use the same button codes as the ED F16? Perhaps that is the issue

**Comment by blueberrypi-studio** [comment]
Thanks for the quick response, I have since got the other f16s working, however, it's not as elegant as I would've hoped.

```js
    case "F-16D_50":
    case "F-16D_50_NS":
    case "F-16D_52":
    case "F-16D_52_NS":
    case "F-16D_Barak_30":
    case "F-16D_Barak_40":
    case "F-16I":
```

thanks for the update about the colour changing, seeing as its done in react its probably a trickier thing to implement, but i will be changing it manually, cheers

**Comment by blueberrypi-studio** [comment]
working on a pull request with images to match too for ya, so you can slip it in the next update if you feel obliged :-)

**Comment by aronCiucu** [comment]
I'll consider changing the color to the same old purple for the next version

**Comment by FalcoGer** [comment]
Would be nice if you could simply replace an image file or have a config option in a json or something to point to a specific file that you want.
I also find the old purple to be more visible.
