### ISSUE TITLE
No connection to DCS.

### ISSUE THREAD

**Issue by angilye** [aronCiucu/DCSTheWay#7]
Hello.

After having followed your instructions for the installation. 
When I launch the .exe, then start selecting on map, when I press Select point. 

I get the message "No connection to DCS." 

Could you help me?

**Comment by aronCiucu** [comment]
Hello, did you put the TheWay.lua file in the correct location as per instructions? Also did you modify your Export.lua file as required? Finally, is DCS actually started and the mission running and unpaused?

**Comment by angilye** [comment]
Yes yes the file is in the "Scripts" folder located "...Saved Games\DCS.openbeta\Scripts"

And the Export file looks like this: https://prnt.sc/1rq018n

And what to say, yes DCS is correctly started since I started my plane (F16) and the server is a multiplayer server with other planes that move so no bug or pause. :s

**Comment by aronCiucu** [comment]
Could you send me the dcs log please? After you tried using the progran

**Comment by angilye** [comment]
Well, I'm sorry, but today it works properly even after several reboot pc or games. 

I don't understand why it didn't work before :s 

Would you still like the logs? 

Great application anyway, thanks to you!

**Comment by aronCiucu** [comment]
Perhaps the server did not have Object exports enabled? And you flew on a different one this time?

**Comment by angilye** [comment]
Apparently it would be because I launch the application after joining the server that it does not work 
But when I launch the application before starting DCS it works and ok I'll send you the logs in the evening
