### ISSUE TITLE
Bug - Selecting points on F10 from spectator role creates points way off

### ISSUE THREAD

**Issue by FalcoGer** [aronCiucu/DCSTheWay#70]
When selecting points from the spectator role on a multiplayer server from the F10 map, the points all end up in the same place and they are nowhere near where the point was initially made.

**Comment by aronCiucu** [comment]
Hi, this appears to be a DCS limitation, in spectator mode the points are taken from some sort of "origin" point on the map.

**Comment by FalcoGer** [comment]
It is not a dcs limitation. you simply don't send the data to the application when no airframe is selected.

https://github.com/aronCiucu/DCSTheWay/blob/main/TheWay.lua#L114C9-L114C18
