### ISSUE TITLE
VR Support

### ISSUE THREAD

**Issue by ToastyBanK3nobi** [aronCiucu/DCSTheWay#78]
Hey, I can't pin the program as a view in steamVR, in other mods this is possible, like in SRS. Is it possible for you to make it?

Thx

**Comment by ozdeadmeat** [comment]
same issue, not seeing any interface in dcs VR, but the green circle is visible looking at the vr export on the monitor. Running openXR with a varjo.

**Comment by ozdeadmeat** [comment]
I recommend taking a look at DCS Scratchpad (https://github.com/rkusa/dcs-scratchpad) as he has an interface that is interactable in VR.

**Comment by gunterlund** [comment]
I dont see the green circle on the map in VR so there is no way to tell where the waypoint will be marked.

**Comment by blueberrypi-studio** [comment]
https://github.com/aronCiucu/DCSTheWay/issues/92#issuecomment-1575473811

**Comment by Quax456** [comment]
Yes, no joy in VR :(

**Comment by korruptcow** [comment]
temp workaround until the circle is implemented

If you install scratchpad you can send the waypoints to theway with the hotkeys. But you use the scratch pad dot to get the right position.

**Comment by aronCiucu** [comment]
Hello, in the next version the crosshair will be visible in VR, and toggled via keybinds
