### ISSUE TITLE
Brand new user, new version looks great, just a couple questions

### ISSUE THREAD

**Issue by salsantana** [aronCiucu/DCSTheWay#79]
From my POV, this is a pioneering achievement. I've been enduring some "no connection to DCS" episodes which brought me here.
Questions I've long had when engaging this app:
1. Is it best practice/necessary to start The Way before starting DCS; does it matter? Can it work properly if DCS is running before engaging The Way?
2. Is it at all useful to set your first point in F-10 map as "0"; does it need a "point of beginning" at coordinates at least near to your position on the runway? I thought I'd seen something about that in discussions, or it could be leftovers from my years in land survey plotting.
Copious thanks for any info..... I'm quite sure I'm barely qualified to mingle among coders, but must say this utility streamlines the near-vertical learning curve of DCS's aircraft.

**Comment by FalcoGer** [comment]
Did you put the script file into DCS and added the line to the exports.lua file?
