### ISSUE TITLE
Feature Request - VR

### ISSUE THREAD

**Issue by Heater711** [aronCiucu/DCSTheWay#8]
Hi, amazing mod, first of all !

I'm an user of VR (Reverb G2) it is possible to use TheWay also via VR ?

Regards,
Andrew

**Comment by aronCiucu** [comment]
Hello, thank you for the appreciation. Unfortunately I do not own any VR hardware so compatibility with virtual reality is so far out of my reach to implement... However a work around could be made if I ever get to make keybinds work with the program, and thus allowing it to be used without clicking on the GUI

**Comment by Heater711** [comment]
Yep, keybindings will be hopefull

**Comment by Heater711** [comment]
Any news about VR feature ?
