### ISSUE TITLE
BUG: A10 Waypoint name too long CDU error

### ISSUE THREAD

**Issue by FalcoGer** [aronCiucu/DCSTheWay#80]
The way seems to allow arbitrary way point name lengths for the A10, but the A10 only allows 12 characters maximum. This results in a CDU error on entry if you type a name longer than that, such as "West Berentin", causing the rest of the input to fail.

**Comment by aronCiucu** [comment]
I will consider limiting the name size for the future

**Comment by aronCiucu** [comment]
HI, this was fixed for the latest release
