### ISSUE TITLE
FR: automatically select the correct mode

### ISSUE THREAD

**Issue by FalcoGer** [aronCiucu/DCSTheWay#82]
Is it at all possible to do stuff like selecting precise mode in the F18 when it isn't selected automatically, or selecting L/L mode in the A10 if it is in UTM, and then switch back afterwards, or determine if you're in the Pilot or CPG seat in the apache?

Can you read from DCS if an entry has produced the desired effect and abort if it didn't instead of continuing to press random buttons at that point? Right now if something fails unexpectedly, the way just keeps on pressing buttons with no way to abort.

It would really help the whole automation stuff.

**Comment by aronCiucu** [comment]
Unfortunately there is no way that I know of to check these things, hence why I have to rely on the user.
