### ISSUE TITLE
FR: Prime correctly for AH64

### ISSUE THREAD

**Issue by FalcoGer** [aronCiucu/DCSTheWay#83]
In the Apache the way doesn't work correctly if one isn't in the TSD/Point/Add submenu when starting the transfer. One can easily get to this correct state by pressing TSD-B6-L3 (I think?). It would be nice if the way did that automatically instead of relying on this obscure knowledge and people not forgetting to do that themselves.

Pressing the TSD quick access button always brings up the top level TSD page, so it's a way to set the display to a known mode, no matter it's state. The only thing that can be different at that point is Nav or Attack phase, which would determine if you make targets or waypoints by default.

But pressing the WP selection also sets a known state, even if WP is already selected, in which case nothing happens. So if you just press WP every time, it doesn't matter if the user has selected attack or navigation phase, making everything deterministic, no matter the initial state.

**Comment by aronCiucu** [comment]
Hi, as far as I know, it is not requred to be in the TSD/Point/Add submenu, the program should do that by itself

**Comment by FalcoGer** [comment]
It does weird things when it's not. At least for me.

**Comment by aronCiucu** [comment]
If you could show me a video when it's not working properly, I can check it out, since I am having trouble reproducing the issue.
