### ISSUE TITLE
Not connected to DCS

### ISSUE THREAD

**Issue by Jormangund1** [aronCiucu/DCSTheWay#85]
I followed the tutorial at export.lua I still have this prompt after writing. At first, I suspected that the port was occupied, but I didn't call the port until I got into the plane.![5a3df13459f8d232.jpg](https://user-images.githubusercontent.com/78534146/235032909-cc660422-b75c-488f-bb55-91f81ca19750.jpg)

![6ce09427f4980f11.jpg](https://user-images.githubusercontent.com/78534146/235032911-de739884-2eb0-4bca-a456-b537077ea3ce.jpg)

![-29dedc604fb74e51.jpg](https://user-images.githubusercontent.com/78534146/235032910-e2d4f7e7-18bb-487f-a1f7-2cc458d30f25.jpg)

![af7162c040dd802.png](https://user-images.githubusercontent.com/78534146/235032908-9b88af93-cc4d-406f-85f8-1f30ca9dec44.png)

**Comment by Tazzzilo** [comment]
I have the same problem. In my DCS log the script is never loaded. Other scripts which are not based on export.lua working fine

**Comment by Jormangund1** [comment]
So, I was wondering if this is a new bug or some other problem. In fact, I was able to use it normally in the version half a year ago, but after a certain update, it was like this

**Comment by Jormangund1** [comment]
> I have the same problem. In my DCS log the script is never loaded. Other scripts which are not based on export.lua working fine

So, I was wondering if this is a new bug or some other problem. In fact, I was able to use it normally in the version half a year ago, but after a certain update, it was like this.

**Comment by aronCiucu** [comment]
@Jormangund1 have you replaced your old TheWay.lua file with the newest one? Other than that, it should work, perhaps there are other factors affecting your machine...

**Comment by Jormangund1** [comment]
> @Jormangund1 have you replaced your old TheWay.lua file with the newest one? Other than that, it should work, perhaps there are other factors affecting your machine... 

I have re-deleted and written the saved in-game DCS, but still not

**Comment by Jormangund1** [comment]
> @Jormangund1 have you replaced your old TheWay.lua file with the newest one? Other than that, it should work, perhaps there are other factors affecting your machine... 
To do this, I looked for port usage, and firewall settings, but even so, it didn't run, Didn't use port 42**** (can't remember port number )

**Comment by Tazzzilo** [comment]
> I have the same problem. In my DCS log the script is never loaded. Other scripts which are not based on export.lua working fine

It magically worked today for the first time. I did not changed anything. It is even the first time in the logs

**Comment by Jormangund1** [comment]
> 

So, is this a bug?

**Comment by aronCiucu** [comment]
It's most probably due to windows or some other side effect, I am not aware of any potential issues that might arise in the code for now

**Comment by Jormangund1** [comment]
> It's most probably due to windows or some other side effect, I am not aware of any potential issues that might arise in the code for now

There is another new topic, so please fix it as soon as possible.

**Comment by MadogPL** [comment]
I also have same issue

**Comment by OfficialDSplayer** [comment]
I'm also having the same issue.

**Comment by aronCiucu** [comment]
Can you guys show me the DCS.log file, so I can check if the .lua file is loading correctly? @Jormangund1 can you also try moving the line in Export.lua to the 1st position? I have the feeling that opening that UDP port in the Export file might have something to do with it

**Comment by MadogPL** [comment]
Ok, just to clarify: I did not do ANYTHING, and it started to work. Waypoint Editor finds it. DCS when in plane finds it. Previously it did not after multiple attempts.
