### ISSUE TITLE
Unable to select install location.

### ISSUE THREAD

**Issue by sicwan** [aronCiucu/DCSTheWay#88]
Title pretty much says it all, when using the setup, I'm not able to pick where to install the app to.

**Comment by aronCiucu** [comment]
Hi, currently the app is being installed at `C:\Users\USER\AppData\Local\Programs\theway` , but I will consider allowing the customization of that location, if the builder framework which I'm using allows it

**Comment by Jimbo4123** [comment]
get a DCS no connection... trying to find where its installed. looked for C:\User\Jim\AppData\local\Programs\theway and can't find it. does the install create these files or do i?
