### ISSUE TITLE
Seems a bit slow

### ISSUE THREAD

**Issue by AG51-Thud** [aronCiucu/DCSTheWay#89]
Greetings.  I just download the v2 version and it seems to take a while to load each new coordinate.  Can I change the speed?

Secondly, if I change the Text from Waypoint 1 to something like TGT-1 is that what is supposed to show? I don't see that.

added: using it with the F-18

**Comment by aronCiucu** [comment]
Hi, please make sure you have replaced your old TheWay.lua file with the newest one. As for the waypoint names, I don't think the Hornet supports named waypoints, but modules like the A10C do.

**Comment by AG51-Thud** [comment]
Excellent, thank you sir.  That was the problem. Its a fairly new build and I didnt recall having v1. 
awesome tool. Thanks for sharing. 
a question, and a comment:

Comment:  There are a few videos out there stating to be on waypoint zero when you import. Thats the case if you have no waypoint already loaded. If you have preloaded waypoints then be on the last waypoint and the import starts at the next a available one.

Question: Where did you find the info to convert the waypoint coordinates?  Since the waypoint text is not imported I was hoping the create a side document from the exported text file.

**Comment by aronCiucu** [comment]
So the exported file has the coordinates the decimal format, and it also includes the names of the points
