### ISSUE TITLE
Wonderfull product

### ISSUE THREAD

**Issue by flasher44** [aronCiucu/DCSTheWay#90]
Please make it compatible with VR, I can help you testing !

**Comment by ToastyBanK3nobi** [comment]
Issue already open...
https://github.com/aronCiucu/DCSTheWay/issues/78

**Comment by aronCiucu** [comment]
Hi, unfortunately I do not have the knowledge to display the GUI over the VR environment, best you can do at the moment is to plan in 2D or use the keybinds...
