### ISSUE TITLE
Saving waypoints in VR uses center of the screen as reference to cursor.

### ISSUE THREAD

**Issue by pubgrub2** [aronCiucu/DCSTheWay#92]
When saving waypoints in VR with the keybind it saves the coordinates of the center point of the map rather than the point under the cursor. The green crosshair does not show either.

**Comment by pubgrub2** [comment]
I installed dcs scratchpad as a substitute as they have a center crosshair

**Comment by blueberrypi-studio** [comment]
Hey guys, I've been using this version in VR no problems on the latest version, it won't show up in your headset, but it will show up on the screen mirror DCS uses, so you take them off that, I just put my headset on my forehead and do it no problem

**Comment by blueberrypi-studio** [comment]
Works in VR is defined as "keybinds", based on a feature request from someone a while ago. I guess it's possible, but idk how, and the creator doesn't have VR so it's not happening unfortunately. But in the interim it works fine

**Comment by aronCiucu** [comment]
Hello, currently this is the only method i can get to make VR work, the points will  be taken from the center of the F10 map, and this is due to a DCS limitation
