### ISSUE TITLE
VR Seat Confirmation Shortcut Support

### ISSUE THREAD

**Issue by PatZab** [aronCiucu/DCSTheWay#93]
Hello, I really like this tool but the VR support is not the best. 

The given shortcuts help but I have to go to the desktop each time I have to confirm that I am in the pilot or cpg seat.

Can you at least add a shortcut for that so I do not have to leave VR?

Thank you in advance.

**Comment by Resin00** [comment]
Same for the hornet, if it isn't too much could we get a disable confirmation option.

Awesome program, thank you

**Comment by aronCiucu** [comment]
Hello, this feature will be released with the next version, you will be able to hide all future confirmation dialogs
