### ISSUE TITLE
no connection to dcs

### ISSUE THREAD

**Issue by aghl22** [aronCiucu/DCSTheWay#97]
Ive tried installing dcs the way several times now, but every time when I try to reinstall it I allways get the same error "no connection to dcs" I dont know if im editing the code in the wrong place but it has yet to work for me.

**Comment by blueberrypi-studio** [comment]
are you editing the export.lua, and adding TheWay.lua? in savedgames/scripts?

**Comment by aghl22** [comment]
its in the right place but i think i have the copy pasted code in the wrong place

**Comment by blueberrypi-studio** [comment]
Yes you have, remove the copied code from "the way.lua" and make a new file called "export.lua" (check the install instructions for the right name, I think the capitals are wrong, but I can't remember) paste the code in the export.lua file.

**Comment by blueberrypi-studio** [comment]
@aghl22 have you run that setup file as well? If you have, and you have a shortcut on your desktop, remove it from your scripts folder. Also similar to my message above. The correct filename is "Export.lua", paste the one line of code in there. Then remove it from "The way.lua", keeping all the original stuff in that file, then you should be good to go

**Comment by aghl22** [comment]
ok I just changed it and its still not working here is what I did. 
![image](https://github.com/aronCiucu/DCSTheWay/assets/135987104/566b32d5-2345-466b-8fac-1cbb111613b7)
![image](https://github.com/aronCiucu/DCSTheWay/assets/135987104/08d28e64-13c3-4756-8811-b26c57dea04a)
![image](https://github.com/aronCiucu/DCSTheWay/assets/135987104/d0516389-6ff3-4be3-bd90-61defbbe369f)

**Comment by blueberrypi-studio** [comment]
Your export.lua is named Export.lua.lua

Just name it Export and it should work. Try turning on file extensions to avoid confusion. (somewhere in the settings of your files app lol)

**Comment by blueberrypi-studio** [comment]
Also both of those .lua files should be in the saved games/DCS.openbeta/scripts folder :-)

**Comment by aghl22** [comment]
I changed it and i still get the message

**Comment by aghl22** [comment]
![image](https://github.com/aronCiucu/DCSTheWay/assets/135987104/71553dda-36af-44e1-a928-5506752f95d4
supposed to happen after i installed it

**Comment by aghl22** [comment]
the way came up this error code

**Comment by aghl22** [comment]
![image](https://github.com/aronCiucu/DCSTheWay/assets/135987104/7dcdf0cf-b86a-4cfc-95a0-510dc4df410c)

**Comment by blueberrypi-studio** [comment]
Try restarting your PC, then get back to me. Could be the source of that error :-)

**Comment by aghl22** [comment]
alr
brb

**Comment by blueberrypi-studio** [comment]
Other thing is make sure you're in a jet, it will say not connected when you're in the menu

**Comment by aghl22** [comment]
it works now holy im so stupid

**Comment by blueberrypi-studio** [comment]
All good 😎. If you can mark this as closed that would be sick 🙏

**Comment by aghl22** [comment]
np thanks for helping me
