### ISSUE TITLE
JavaScript error, uncaught exception

### ISSUE THREAD

**Issue by Razgriz1032** [aronCiucu/DCSTheWay#98]
When attempting to run TheWay, I encounter an error and TheWay remains disconnected from DCS.
![image](https://github.com/aronCiucu/DCSTheWay/assets/15962836/daf94090-b398-4868-a46c-8182cba1ce64)

TheWay.lua is placed in my DCSbeta saved games script folder. Export.lua has the line "local TheWayLfs=require('lfs'); dofile(TheWayLfs.writedir()..'Scripts/TheWay.lua')" added to it at the bottom. I am running on Windows 10

Is there any more information I can give you or that you can give me?

**Comment by darman117** [comment]
I have the same issue. Is there a file or log I can send?

**Comment by blueberrypi-studio** [comment]
@Razgriz1032 @darman117 does it work at all? This error is caused by running the app a second time, while the first app is still open. This can be resolved immediately by restarting your PC or just closing both and waiting approx 10 mins

Let me know how that goes

**Comment by blueberrypi-studio** [comment]
Also it's worth noting that you need to be in a jet to not see the "not connected to DCS" message, this has caught a few people out before

**Comment by Razgriz1032** [comment]
I could definitely have sworn that I had end tasked the thing before so that there was no second process. But now that I have power cycled the computer, it's fine now. I'll just close this then, you're right. I am able to replicate it by attempting to run two instances again.

**Comment by blueberrypi-studio** [comment]
If you do it by mistake again, the original one open will still work. (I do it all the time) also even if you close the first one, through task manager, it still has the port reserved. It's a weird quirk of networked programming sometimes. Power cycle is quickest fix 😁😁
